### How to Do Linear Regression in Python

In [1]:
import numpy as np

In [39]:
a = np.random.randint(1,3,5) # from, to, n
b = np.random.randint(0,10,5) # from, to, n
print(a)
print(b)

[1 1 2 1 1]
[1 1 0 0 8]


In [40]:
print(np.subtract(b,a)) # Subtrair elemento a elemento
print(np.add(b,a)) # Somar elemento a elemento
print(np.divide(a,b))  # Dividir elemento a elemento
print(np.multiply(a,b))  # Multiplicar elemento a elemento

[ 0  0 -2 -1  7]
[2 2 2 1 9]
[1.    1.      inf   inf 0.125]
[1 1 0 0 8]


In [41]:
print(np.exp(a))
print(np.sqrt(a))
print(np.sin(a))
print(np.log(a))  
print(np.log2(a))  

[2.71828183 2.71828183 7.3890561  2.71828183 2.71828183]
[1.         1.         1.41421356 1.         1.        ]
[0.84147098 0.84147098 0.90929743 0.84147098 0.84147098]
[0.         0.         0.69314718 0.         0.        ]
[0. 0. 1. 0. 0.]


In [42]:
c = np.random.rand(5)
print(c)
print(np.around(c))

[0.03597923 0.61161908 0.89560878 0.21927648 0.7714321 ]
[0. 1. 1. 0. 1.]
