### How to use Numpy

In [1]:
import numpy as np

[1 1 2 1 1]
[1 1 0 0 8]


[ 0  0 -2 -1  7]
[2 2 2 1 9]
[1.    1.      inf   inf 0.125]
[1 1 0 0 8]


[2.71828183 2.71828183 7.3890561  2.71828183 2.71828183]
[1.         1.         1.41421356 1.         1.        ]
[0.84147098 0.84147098 0.90929743 0.84147098 0.84147098]
[0.         0.         0.69314718 0.         0.        ]
[0. 0. 1. 0. 0.]


[0.03597923 0.61161908 0.89560878 0.21927648 0.7714321 ]
[0. 1. 1. 0. 1.]
