# Solving some Linear algebra excersises in Python

### First, let's import some libraries

In [9]:
import numpy as np

### Then, let's get a matrix

In [30]:
a = np.array([[10, 20, 30], [40, 50, 60]], dtype = int)
print(a)
print("A matrix a é do tipo: ",type(a))

[[10 20 30]
 [40 50 60]]
A matrix a é do tipo:  <class 'numpy.ndarray'>


In [42]:
b = np.arange(9).reshape(3, 3)
print(b)
print("A matrix b é do tipo: ",type(b))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
A matrix b é do tipo:  <class 'numpy.ndarray'>


### To multiply two matrices, we use dot() method. Learn more about how numpy.dot works.
### Note: * is used for array multiplication (multiplication of corresponding elements of two arrays) not matrix multiplication.

In [50]:
c = np.dot(a, b)
print(c)

[[240 300 360]
 [510 660 810]]


In [53]:
ct = c.transpose()
print(ct)

[[240 510]
 [300 660]
 [360 810]]


In [62]:
print("ct[0][0] =",ct[0])
print("ct[0][0] =",ct[0][0])
print("ct[0][0] =",ct[0][1])
print("ct[1][0] =",ct[1][0])
print("ct[2][0] =",ct[2][0])
print("ct[2][1] =",ct[2][1])

ct[0][0] = [240 510]
ct[0][0] = 240
ct[0][0] = 510
ct[1][0] = 300
ct[2][0] = 360
ct[2][1] = 810


In [63]:
ct[0][0] = 666
ct[2][1] = 666

In [67]:
print("New ct equals: \n",ct)

New ct equals: 
 [[666 510]
 [300 660]
 [360 666]]


In [70]:
print("ct[:,0] =",ct[:,0]) # First Column
print("ct[:,1] =", ct[:,1]) # Second column 

ct[:,0] = [666 300 360]
ct[:,1] = [510 660 666]


### Identity matrixes are such like these:

In [79]:
print("Identity matrix 3x3\n",np.eye(3),"\n")
print("Identity matrix 4x4\n",np.eye(4))

Identity matrix 3x3
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

Identity matrix 4x4
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### Computing inverse of a matrix is one of the important concepts and has many useful applications. Not all matrices can have inverse. Finding an inverse of a matrix A is find a matrix B such that the product of A with B is the identity matrix.

#### NumPy’s linalg module has the function inv

In [88]:
d = np.array([[1,2,3], [10,5,6],[7,8,9]])
print(d)

d_inv = np.linalg.inv(d)
print(d_inv)

[[ 1  2  3]
 [10  5  6]
 [ 7  8  9]]
[[-0.08333333  0.16666667 -0.08333333]
 [-1.33333333 -0.33333333  0.66666667]
 [ 1.25        0.16666667 -0.41666667]]


### As stated earlier, the multiplication of a matrix and its inverse is equal an identity matrix

In [93]:
print(np.dot(d,np.linalg.inv(d),))

[[ 1.00000000e+00  5.55111512e-17  0.00000000e+00]
 [-4.44089210e-16  1.00000000e+00 -4.44089210e-16]
 [ 2.22044605e-16  1.66533454e-16  1.00000000e+00]]


In [96]:
print("Is the result close enough to be considered equal? ",np.allclose(np.dot(b, b_inv), np.eye(3)))

Is the result close enough to be considered equal?  True


### We can also have the trace of a matrix, which is the sum of main diagonal 

In [99]:
print(np.trace(d))

15


### Finally, we can compute the determinant of a matrix

In [104]:
print("The determinant of the matrix d is euqals:",int(np.linalg.det(d)))

The determinant of the matrix d is euqals: 36


### Let's create a matrix from a diagonal

In [108]:
e = np.diag((3, 4, 5))
print("A matrix e foi criada a partir de sua diagonal, perceba:\n",e)

A matrix e foi criada a partir de sua diagonal, perceba:
 [[3 0 0]
 [0 4 0]
 [0 0 5]]
